### ISSUE TITLE
compatibility with PHP 7

### ISSUE THREAD

**Issue by countless-integers** [Atriedes/tactician-service-provider#5]
composer constraint prevents it to be installed on machines with PHP7. Is this intended behaviour?

**Comment by praswicaksono** [comment]
yes, I havent tested with PHP7, PR are welcome by the way

change this line : https://github.com/praswicaksono/tactician-service-provider/blob/master/composer.json#L8

to "^5.5 | ^7.0" if you wish to install on php 7

**Comment by countless-integers** [comment]
Yeah, turns out I got more dependency problems as I cannot use silex 2.\* dev with the new pimple and all that. Heh. Guess I'll have to work around that somehow.
